### ISSUE TITLE
Connection Delay not work. 

### ISSUE THREAD

**Issue by lwj94** [gpvigano/M2MqttUnity#11]
### Environment
* version of M2MqttUnity: 9a030e5b1021e9ac7c419621b2407306a744f138
* version of Unity3D: 2020.3.19f

### Expected behavior

> We expected connection delay in 10ms. So we code connectionDelay = 10; 

### Current behavior

> But we get approximately 900ms.

**Comment by gpvigano** [comment]
`connectionDelay` make your client wait the specified milliseconds **before connecting**. With 900ms do you mean **before connecting** or **the whole time to estabilish a connection** (that cannot be controlled by the connection delay parameter)?
