### ISSUE TITLE
M2MqttUnity not working with HiveMQ Broker

### ISSUE THREAD

**Issue by akshaysunagar** [gpvigano/M2MqttUnity#13]
Hello,

The code works well for Eclipse IoT MQTT broker (iot.eclipse.org and mqtt.eclipseprojects.io), but if i try the MQTT project with other MQTT brokers like HiveMQ, the script is throwing an exception (screenshot attached).

Has anyone tried to use this package with a different MQTT broker other than Eclipse IoT Broker?
![2021-11-10_19h59_21](https://user-images.githubusercontent.com/61426763/141131583-b7bd244e-f2fa-4091-9a8a-7e3304545ff0.png)
.

**Comment by matthewgani** [comment]
Hi @akshaysunagar did you manage to solve this problem? For the other brokers, it only seems to work when im using the port 1883 without encryption.

**Comment by BurakKaragol** [comment]
Hi @akshaysunagar i am also experiencing the same isssue. Did you managed to find a solution?
I get the same exception
![image](https://user-images.githubusercontent.com/34738016/212969263-38ef9ce1-33e8-4070-bb92-cb59f350febb.png)

**Comment by Tomz295** [comment]
Im also using HiveMQ, and encountered the same issue.
However, setting the **`Is Encrypted`** option to **`True`** (or ticking the box) seems to have solved the issue.

**Comment by akshaysunagar** [comment]
> Hi @akshaysunagar did you manage to solve this problem? For the other brokers, it only seems to work when im using the port 1883 without encryption.

Hi @matthewgani, we used Node-RED REST API-to-MQTT work around to solve this.
We are not using this M2MqttUnity anymore.

**Comment by akshaysunagar** [comment]
> Im also using HiveMQ, and encountered the same issue. However, setting the **`Is Encrypted`** option to **`True`** (or ticking the box) seems to have solved the issue.

Hi @Tomz295, this is good news!
If this works, we do not the Node-RED workaround and can directly communicate with MQTT from Unity.

I will try this out and revert back. Thanks for posting your comment

**Comment by akshaysunagar** [comment]
Hello Everyone, the issue is solved now.

My MQTT broker had a username and password security credentials to connect to it.
I added the username and password to M2MQTTUnityTest.cs and it is working as expected

I am closing this issue now

<img width="426" alt="Screenshot 2023-11-07 at 8 21 17 PM" src="https://github.com/gpvigano/M2MqttUnity/assets/61426763/82bad278-2f17-4162-a0d7-7e21224ebd9a">
<img width="426" alt="Screenshot 2023-11-07 at 8 21 17 PM" src="https://github.com/gpvigano/M2MqttUnity/assets/61426763/5e9c4b17-4613-4d3d-9f30-5433a4d221c5">
