### ISSUE TITLE
Subscribe to multiple topics at once?

### ISSUE THREAD

**Issue by mecadiego113** [gpvigano/M2MqttUnity#17]
Hello there!

I'm using a single MQTT client, but when I try to subscribe tu multiple MQTT topics at the same time I'm receiving errors (when only one topic is subscribed everything works well)

**Comment by GNVR-Dev** [comment]
Just found this issue as well.
Did you find a solution?
This works:
client.Subscribe(new string[] { "M2MQTT_Unity/test" }, new byte[] { MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE });
This does not
client.Subscribe(new string[] { "M2MQTT_Unity/test" ,  "M2MQTT_Unity/test2" }, new byte[] { MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE });
Also tried:
client.Subscribe(new string[] { "myTest1" ,  "myTest2" }, new byte[] { MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE });
but it didn't work either

**Comment by GNVR-Dev** [comment]
I think I figured it out:
First issue - need to have the same qty of topics and QOS Levels so:
`client.Subscribe(new string[] { "M2MQTT_Unity/test1", "M2MQTT_Unity/test2"}, new byte[] { MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE, MqttMsgBase.QOS_LEVEL_EXACTLY_ONCE});`
Second issue:
in M2Mqtt/Messages/ MqttMsgSubscribe.cs the IF statements in GetBytes don't have opening and closing brackets

**Comment by GNVR-Dev** [comment]
made changes and submitted Pull Request 👍 
hmmm. I should do a Pull request to the main project but it looks like a hassle. (legal forms and stuff)

**Comment by gpvigano** [comment]
@GNVR-Dev  Thank you for your contribution. Can I assume your [answer](https://github.com/gpvigano/M2MqttUnity/issues/17#issuecomment-2310622156) (to the first issue you mentioned above) as definitive and close this issue?

**Comment by GNVR-Dev** [comment]
Yes. I would say so. Thank you. 💯

**Comment by gpvigano** [comment]
You're welcome.
