### ISSUE TITLE
is it compatible on ios?

### ISSUE THREAD

**Issue by rinekso** [gpvigano/M2MqttUnity#4]

**Comment by gpvigano** [comment]
I cannot test the compatibility with iOS, but that platform is not explicitly mentioned by [M2MQTT](https://github.com/eclipse/paho.mqtt.m2mqtt), used by this project, even if supports .NET and mono platforms.

Maybe someone else can better answer to this question after testing this project on an iOS platform (I have no access to such devices).

**Comment by CPogolski** [comment]
I have tested the compatibility with iOS and it works with **Unity 2019.3.13f1** + MacOS Catalina 10.15.5 and an iPad Pro 4th Gen with **iPadOS 13.5.1**.

By switching to iOS I needed to add some Namespaces.

**Comment by gpvigano** [comment]
I merged your PR. Thank you very much for your contribution and sorry for the delay, but I was unable to respond before.
